language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-dev \
pkg-config \
libavformat-dev libavcodec-dev libavdevice-dev \
libavutil-dev libswscale-dev libswresample-dev libavfilter-dev \
ffmpeg \
mplayer
  - sudo apt-get clean
  - sudo apt-get autoclean
install:
  - pip install -r requirements.txt
  - pip install pylint
script: python3 -m pylint --errors-only src/*
