language: python
python:
  - "3.7"
addons:
  apt:
    packages:
      - python-dev
      - pkg-config
      - libavformat-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavutil-dev
      - libswscale-dev
      - libswresample-dev
      - libavfilter-dev
      - mplayer
before_install:
  - ./travis/travis-install-ffmpeg.sh
install:
  - pip install pipenv pylint
  - pipenv install
script: pipenv run python -m pylint --errors-only src/*
