language: python
python:
  - "3.7"
env:
  - PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig/"
addons:
  apt:
    packages:
      - python-dev
      - pkg-config
      - libavformat-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavutil-dev
      - libswscale-dev
      - libswresample-dev
      - libavfilter-dev
      - mplayer
install:
  - pip install pipenv pylint
  - pipenv install
script: pipenv run python -m pylint --errors-only src/*
