language: python
python:
  - "3.7"
addons:
  apt:
    packages:
      - python-dev
      - pkg-config
      - libavformat-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavutil-dev
      - libswscale-dev
      - libswresample-dev
      - libavfilter-dev
      - ffmpeg
      - mplayer
install:
  - pip install pipenv pylint
  - pipenv install
script: python3 -m pylint --errors-only src/*
